// Local-only, bounded collector for public test frames generated by full-bench.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const output=path.resolve('.cache/full-brain/validation');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{
  res.setHeader('Access-Control-Allow-Origin','http://127.0.0.1:5173');
  if(req.method!=='POST'||req.url!=='/result'){res.writeHead(404);res.end();return;}
  const chunks=[];let size=0;
  req.on('data',data=>{size+=data.length;if(size>16000000){req.destroy();return;}chunks.push(data);});
  req.on('end',()=>{try{
    const record=JSON.parse(Buffer.concat(chunks).toString());
    if(!/^[a-z0-9_-]{1,50}$/.test(record.label)||!['frame','summary'].includes(record.kind))throw Error('Invalid record');
    if(record.kind==='frame'&&!['map01','map02','map03'].includes(record.clip))throw Error('Invalid public test clip');
    const name=record.label+'-'+(record.kind==='summary'?'summary':record.clip)+'.json';
    fs.writeFileSync(path.join(output,name),JSON.stringify(record));res.end('saved');console.log(name);
  }catch(error){res.writeHead(400);res.end(String(error));}});
});
server.listen(8768,'127.0.0.1',()=>console.log('Public full-brain validation collector: http://127.0.0.1:8768/result'));
