import {chromium} from '@playwright/test';import fs from 'node:fs';import assert from 'node:assert/strict';import path from 'node:path';
const b=await chromium.launch({headless:true,args:['--use-angle=metal']});
try{const p=await b.newPage({viewport:{width:1600,height:1040},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.argv[2]??'http://127.0.0.1:5173/live.html?paused');await p.locator('#live-experiment[data-ready="true"]').waitFor({timeout:120000});const app=p.locator('#live-experiment');
 await p.locator('#live-file').setInputFiles(path.resolve('public/data/live-clips/freedoom-35fps.mp4'));await p.getByText('freedoom-35fps.mp4',{exact:true}).waitFor();await p.locator('#live-play').click();await p.waitForTimeout(20000);await p.locator('#live-play').click();await p.waitForTimeout(250);
 const data=await app.evaluate(el=>({...el.dataset}));const rows=JSON.parse(data.measurements),stats=k=>({mean:rows.reduce((s,x)=>s+x[k],0)/rows.length,p95:rows.map(x=>x[k]).sort((a,b)=>a-b)[Math.floor(rows.length*.95)]});
 const performance={frames:Number(data.frames),fps:(rows.length-1)*1000/(rows.at(-1).at-rows[0].at),processing:stats('latency'),decoded:stats('decodedLatency'),compute:stats('compute'),body:stats('body'),adapter:data.backend};fs.writeFileSync('.cache/large-control/live160-file-throughput.json',JSON.stringify({performance,data},null,2));console.log(JSON.stringify(performance));
 const image=()=>p.locator('#live-brain canvas').evaluate(c=>c.toDataURL());const before=await image(),state=await app.getAttribute('data-spikes');await p.locator('#live-seek').fill('5');await p.waitForTimeout(200);assert.equal(await image(),before,'paused source seek must not repaint brain');assert.equal(await app.getAttribute('data-spikes'),state);
 await p.locator('#live-soften').uncheck();await p.waitForTimeout(150);assert.notEqual(await image(),before,'raw-light toggle redraws while paused');await p.locator('#live-soften').check();await p.locator('#live-brain-view').selectOption('side');await p.waitForTimeout(200);assert.notEqual(await image(),before,'orbit changes real geometry');await p.screenshot({path:'.cache/screenshots/live160-side.png'});await p.locator('#live-brain-view').selectOption('image');
 await p.locator('#live-representation').selectOption('branches');await p.locator('#site-caption').filter({hasText:'whole sampled arbors'}).waitFor({timeout:30000});await p.waitForTimeout(100);assert.notEqual(await image(),before,'branch geometry redraws while paused');await p.screenshot({path:'.cache/screenshots/live160-branches.png'});await p.locator('#live-representation').selectOption('sites');await p.locator('#site-caption').filter({hasText:'one fixed site each'}).waitFor();
 const downloadPromise=p.waitForEvent('download');await p.locator('#live-save').click();const download=await downloadPromise;await download.saveAs('.cache/screenshots/live160-saved.png');
 await p.locator('#live-synapses').uncheck();await p.locator('#live-reset').click();await p.waitForTimeout(200);await p.locator('#live-play').click();await p.waitForTimeout(1000);await p.locator('#live-play').click();await p.waitForTimeout(200);assert.ok(Number(await app.getAttribute('data-spikes'))>0,'upstream spikes remain');assert.equal(await app.getAttribute('data-deliveries'),'0');assert.equal(await app.getAttribute('data-maximum-activity'),'0','all displayed cells dark after cutting synapses');
 await p.locator('#live-file').setInputFiles({name:'unsupported.mp4',mimeType:'video/mp4',buffer:Buffer.from('not a video')});await p.getByText('This browser could not decode the video.',{exact:false}).waitFor();await p.locator('#live-clip').selectOption('live-clips/map02.mp4');await p.getByText('Loading bay',{exact:true}).last().waitFor();assert.equal(await app.getAttribute('data-ready'),'true');
 await p.setViewportSize({width:390,height:844});await p.waitForTimeout(150);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'.cache/screenshots/live160-mobile.png',fullPage:true});
 fs.writeFileSync('.cache/large-control/live160-controls.json',JSON.stringify({passed:true,errors,checks:['local MP4','distinct frame throughput','paused seek independent of brain','blur toggle while paused','real-geometry orbit','whole-arbor switch','PNG export','cut synapses gives zero downstream with upstream firing','unsupported codec and recovery','390px layout']}));assert.deepEqual(errors,[]);console.log('Live controls passed');
}finally{await b.close();}
