import {GpuCircuit} from './gpu-circuit';
import {GpuImageController} from './gpu-controller';
import {GpuPixelController} from './gpu-pixel-controller';
import {FlyBodyView} from './body';
import {motorReadout} from './neural';
const result=document.getElementById('result')!;
try{
  const response=await fetch('/data/connectome.bin.gz');const raw=await response.arrayBuffer();
  const buffer=new Uint8Array(raw)[0]===31?await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():raw;
  const query=new URL(location.href).searchParams;const large=query.has('large'),sites=query.has('sites');const width=sites?Number(query.get('width')??160):320,height=width*3/4;
  const meta=await (await fetch(query.has('selected')?'/data/'+(query.get('selected')||'selected-'+width)+'/controller.json':large?(query.has('all')?'/data/large/controller-99999.json':'/data/large/controller-2.json'):'/data/presynaptic-controller.json')).json();
  // Causal intervention only: permute postsynaptic identities among displayed
  // cells while retaining presynaptic degrees, weights and actuator identities.
  if(query.has('shuffle')){const header=new Uint32Array(buffer,0,3),n=header[1],e=header[2],posts=new Uint32Array(buffer,12+4*(n+1),e);const shuffled=meta.outputIds.slice();let seed=784;for(let i=shuffled.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}const map=new Int32Array(n).fill(-1);meta.outputIds.forEach((id:number,i:number)=>map[id]=shuffled[i]);for(let i=0;i<e;i++)if(map[posts[i]]>=0)posts[i]=map[posts[i]];}
  const circuit=await GpuCircuit.create(buffer,{observation:query.get('observation')??'exponential',traceMs:Number(query.get('trace')??100),largeBufferBytes:query.has('admm')?width*height*width*height*4:undefined});
  let controller:GpuImageController|GpuPixelController|null=null,project:((cells:Float32Array)=>number[])|null=null,target:number[]=[];
  if(new URL(location.href).searchParams.has('control')){
    const op=await (await fetch(query.has('selected')?'/data/'+(query.get('selected')||'selected-'+width)+'/operator.bin':large?(sites?`/data/large/sites-${width}.bin`:'/data/large/operator-320.bin'):'/data/synaptic-image-operator.bin')).arrayBuffer();
    const header=new Uint32Array(op,0,large?4:3),[p,n,e]=large?Array.from(header).slice(1):Array.from(header);
    const row=large?new Uint32Array(op,16,e):new Uint16Array(op,12,e),column=large?new Uint32Array(op,16+4*e,e):new Uint16Array(op,12+2*e,e),weight=new Float32Array(op,large?16+8*e:12+4*e,e);
    controller=new (query.has('pixel')?GpuPixelController:GpuImageController)(circuit,meta,{rows:p,columns:n,row,column,weight},[],{inputRatePenalty:Number(query.get('energy')??0),kp:Number(query.get('kp')??.5),ki:Number(query.get('ki')??4),antiwindup:Number(query.get('antiwindup')??20),integralLimit:Number(query.get('integralLimit')??50),initialIterations:Number(query.get('initial')??64),maintenance:Number(query.get('maintenance')??2),rateMode:query.has('rateMode'),inverse:query.has('admm')?new Float32Array(await (await fetch('/data/large/control-inverse-'+width+'.bin')).arrayBuffer()):undefined,gradientLimit:Number(query.get('gradient')??5),ridge:Number(query.get('ridge')??.001),maxControlDegree:Number(query.get('degree')??Infinity),robust:query.has('robust'),compensate:query.has('compensate'),inputMode:query.has('clamp')?2:1,rateScale:Number(query.get('rate')??60),imageIterations:sites?1:40,feedbackTicks:Number(query.get('interval')??25),controlIterations:Number(query.get('iterations')??6)});
    if(large){
      const image=new Image();image.src=query.get('frame')??'/data/live-clips/map01-0.png';await image.decode();const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d')!;context.drawImage(image,0,0,width,height);const pixels=context.getImageData(0,0,width,height).data;target=Array.from({length:p},(_,i)=>(.2126*pixels[i*4]+.7152*pixels[i*4+1]+.0722*pixels[i*4+2])/255);
    }else target=(await (await fetch('/data/synaptic-control-validation.json')).json()).runs[0].frames[8].target;
    project=cells=>{const output=new Float64Array(p);for(let i=0;i<e;i++)output[row[i]]+=weight[i]*Math.min(1,cells[meta.outputIds[column[i]]*5+2]/(controller!.rateScale*circuit.traceMs/1000));return Array.from(output);};
  }else circuit.setInputs(meta.inputIds,new Float32Array(meta.inputIds.length).fill(800));
  let body:FlyBodyView|null=null;let circuitMeta=null;if(query.has('body')){const element=document.createElement('div');element.style.cssText='width:500px;height:500px';document.body.append(element);body=new FlyBodyView(element);await body.load(()=>{});body.setTimestep(Number(query.get('bodyDt')??.0001));circuitMeta=await (await fetch('/data/connectome.json')).json();}
  let video:HTMLVideoElement|null=null,videoContext:CanvasRenderingContext2D|null=null;
  if(query.has('video')){video=document.createElement('video');video.muted=true;video.preload='auto';video.src=query.get('video')!;await new Promise<void>((resolve,reject)=>{video!.onloadeddata=()=>resolve();video!.onerror=()=>reject(Error('Cannot decode sequence'));video!.load();});const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;videoContext=canvas.getContext('2d',{willReadFrequently:true})!;}
  const sequence:{index:number;mse:number;prediction:number[];target:number[];countPrediction?:number[]}[]=[];let previousCounts=new Uint32Array(circuit.n);
  const timings=[],bodyTimings=[];let observed=null;
  for(let i=0;i<Number(query.get('steps')??5);i++){
   if(query.has('pattern')){const cell=Number(query.get('pattern')??3);target=Array.from({length:width*height},(_,j)=>.1+.7*((Math.floor((j%width)/cell)+Math.floor(Math.floor(j/width)/cell)+i)%2));}
   if(video){const time=(i*.1)%video.duration;if(Math.abs(video.currentTime-time)>1e-6){await new Promise<void>(resolve=>{video!.onseeked=()=>resolve();video!.currentTime=time;});}videoContext!.drawImage(video,0,0,width,height);const rgba=videoContext!.getImageData(0,0,width,height).data;target=Array.from({length:width*height},(_,j)=>(.2126*rgba[j*4]+.7152*rgba[j*4+1]+.0722*rgba[j*4+2])/255);}
   const start=performance.now();controller?.setFrame(target);observed=await circuit.advance(100,true,controller?(pass,tick)=>controller!.encode(pass,tick):undefined);const bodyStart=performance.now();if(body){const motor=motorReadout(circuitMeta!,{rateHz:id=>observed!.cells[id*5+2]*1000/circuit.traceMs});body.step(100,motor.left,motor.right);body.render();}bodyTimings.push(performance.now()-bodyStart);timings.push(performance.now()-start);if(video||query.has('pattern')){const prediction=project!(observed!.cells);const countCells=observed!.cells.slice();for(let n=0;n<circuit.n;n++)countCells[n*5+2]=((observed!.counts[n]-previousCounts[n])>>>0)*circuit.traceMs/100;previousCounts=observed!.counts.slice();const countPrediction=project!(countCells);const frame={countPrediction,index:i,mse:prediction.reduce((sum,x,j)=>sum+(x-target[j])**2,0)/target.length,prediction,target};if(query.has('collector')){const response=await fetch(query.get('collector')!+'/frame',{method:'POST',body:JSON.stringify(frame)});if(!response.ok)throw Error('Validation collector failed.');}else sequence.push(frame);}result.textContent=JSON.stringify({timings,spikes:observed?.spikes,deliveries:observed?.deliveries});}
  const prediction=project?.(observed!.cells),mse=prediction?.reduce((s,x,i)=>s+(x-target[i])**2,0)!/target.length;
  let diagnostics=null,snapshot=null;
  if(controller){const device=circuit.device;const read=async(b:GPUBuffer)=>{const stage=device.createBuffer({size:b.size,usage:GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST});const e=device.createCommandEncoder();e.copyBufferToBuffer(b,0,stage,0,b.size);device.queue.submit([e.finish()]);await stage.mapAsync(GPUMapMode.READ);const result=new Float32Array(stage.getMappedRange().slice(0));stage.unmap();stage.destroy();return result;};
   const q=await read(controller.current.states),residual=await read(controller.current.residual);let squared=0,norm=0,upper=0,zero=0;for(let i=0;i<residual.length;i+=2){norm+=residual[i]**2;squared+=residual[i+1]**2;}for(let i=0;i<q.length;i+=4){if(q[i]>.99*q[i+2])upper++;if(q[i]<1e-5)zero++;}if(query.has('snapshot'))snapshot={q:Array.from(q),target:Array.from(residual).filter((_,i)=>i%2===0)};diagnostics={currentResidualRms:Math.sqrt(squared/(residual.length/2)),currentTargetRms:Math.sqrt(norm/(residual.length/2)),saturatedInputs:upper,inactiveInputs:zero};
  }
  circuit.synapsesEnabled=false;circuit.reset();const disconnected=await circuit.advance(100);
  const maximumOutput=meta.outputIds.reduce((max:number,id:number)=>Math.max(max,disconnected!.cells[id*5+2]),0);
  result.textContent=JSON.stringify({status:'done',sequence,diagnostics,snapshot,bodyState:body?.getState(),timings,bodyTimings,adapter:{...circuit.device.adapterInfo,subgroupMin:circuit.device.adapterInfo.subgroupMinSize,subgroupMax:circuit.device.adapterInfo.subgroupMaxSize},spikes:observed?.spikes,deliveries:observed?.deliveries,maximumOutput,disconnectedSpikes:disconnected!.spikes,disconnectedDeliveries:disconnected!.deliveries,shuffled:query.has('shuffle'),mse,prediction,target,outputRates:meta.outputIds.map((id:number)=>observed!.cells[id*5+2]*1000/circuit.traceMs)});
  document.body.dataset.done='true';body?.dispose();controller?.destroy();circuit.destroy();
}catch(error){result.textContent=String(error);document.body.dataset.error='true';console.error(error);}
